
// Objective-C API for talking to the following Go packages
//
//	goSwift
//
// File is generated by gomobile bind. Do not edit.
#ifndef __GoSwift_FRAMEWORK_H__
#define __GoSwift_FRAMEWORK_H__

#include "GoSwift.objc.h"
#include "Universe.objc.h"

#endif
