// Objective-C API for talking to goSwift Go package.
//   gobind -lang=objc goSwift
//
// File is generated by gobind. Do not edit.

#ifndef __GoSwift_H__
#define __GoSwift_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT long GoSwiftAdd(long number1, long number2);

FOUNDATION_EXPORT long GoSwiftMultiply(long number1, long number2);

FOUNDATION_EXPORT NSString* _Nonnull GoSwiftTheNewMovie(void);

FOUNDATION_EXPORT NSString* _Nonnull GoSwiftTheNewMovieDays(void);

FOUNDATION_EXPORT NSString* _Nonnull GoSwiftTheNewMovieImage(void);

#endif
